name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t upload-ai .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 3600
      - name: Tag image
        run:
          docker tag upload-ai registry.digitalocean.com/eureka-ai-app/upload-ai:latest
      - name: List docker images
        run: docker image ls
      - name: Push Docker Image and Capture Errors
        run: |
          docker push registry.digitalocean.com/eureka-ai-app/upload-ai:latest
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker pull registry.digitalocean.com/eureka-ai-app/upload-ai:latest
            docker stop eureka-ai-app || true
            docker rm eureka-ai-app || true
            docker run -d --name eureka-ai-app -p 8080:8080 registry.digitalocean.com/eureka-ai-app/upload-ai:latest
